version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27018:27017" # Ensure this is not conflicting
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
